### ISSUE TITLE
galaxy.yml is missing

### ISSUE THREAD

**Issue by atrawog** [maresb/ansible-micromamba-role#1]
The collection is missing a [galaxy.yml](https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html) metadata file. Resulting in an error when you try to install the role directly from github.
```
$ ansible-galaxy collection install git+https://github.com:/maresb/ansible-micromamba-role
ERROR! Neither the collection requirement entry key 'name', nor 'source' point to a concrete resolvable collection artifact. Also 'name' is not an FQCN. A valid collection name must be in the format <namespace>.<collection>. Please make sure that the namespace and the collection name  contain characters from [a-zA-Z0-9_] only.
```

**Comment by maresb** [comment]
That's because this is a role, not a collection. The correct command is

```
ansible-galaxy role install git+https://github.com:/maresb/ansible-micromamba-role
```

In my limited experience, I have been sorely disappointed so far with Ansible's support for collections. I think I'd prefer to keep this a role for now until Ansible works out all the issues.

Maybe it's okay to convert it into a collection, but is there a compelling reason to do so?
